language: php
sudo: false
php:
- 5.5
- 5.6
install:
- composer self-update
- composer config --global github-oauth.github.com $GITHUB_ACCESS_TOKEN
- composer global require "fxp/composer-asset-plugin"
- composer install
