site_name: Mustache for Yii
site_description: Mustache templating for the Yii Framework.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/yii2-mustache

docs_dir: ../doc
site_dir: ../www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/yii2-mustache
edit_uri: ''

copyright: Copyright &copy; 2014 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://belin.io'
    - icon: fontawesome/brands/github
      link: 'https://github.com/cedx'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/cedxbelin'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/cedxbelin'

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - About:
      - License: about/license.md
      - See also: about/see_also.md

theme:
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  favicon: img/favicon.ico
  palette:
    accent: indigo
    primary: indigo
